export const AppConfig = {
    WHATSAPP_API_KEY: process.env.WHATSAPP_API_KEY,
    WHATSAPP_API_VERSION: process.env.WHATSAPP_API_VERSION,
    WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID,
    WHATSAPP_CHALLANGE_KEY: process.env.WHATSAPP_CHALLANGE_KEY,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
}